version: '3.8'

services:
  casanovogui:
    image: pgarrettscripps/casanovogui
    ports:
      - "8510:8501"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - casanovogui_data:/root/.local/share/CasanovoGui

volumes:
  casanovogui_data:
    name: casanovogui_data
